### PR TITLE
Fix/endianness

### LINKED ISSUE #123: Handle endianness for non-native integers
To test in the CI, perhaps we could easily build a cross-compiler using one of these tools:

 * https://crosstool-ng.github.io/
 * https://www.embtoolkit.org/
 * https://gist.github.com/preshing/41d5c7248dea16238b60

### LINKED ISSUE #124: Add CI to test that the endianness of non-native integer is correctly supported
Requires #123

### LINKED ISSUE #258: Stop depending on compiler-rt
To make 128-bit integers work on `#[no_core]`.

### PR DESCRIPTION
**Pull request by antoyo**
Fix #258.
Fix #123.
Fix #124.

### CODE REVIEW

**Comment by antoyo** [comment]
Do not forget to fix this: https://github.com/rust-lang/rustc_codegen_gcc/issues/339

File: build_sysroot/build_sysroot.sh [hunk 1]
```diff
@@ -22,7 +22,8 @@ if [[ "$1" == "--release" ]]; then
     RUSTFLAGS="$RUSTFLAGS -Zmir-opt-level=3" cargo build --target $TARGET_TRIPLE --release
 else
     sysroot_channel='debug'
-    cargo build --target $TARGET_TRIPLE --features compiler_builtins/c
+    # TODO: add flags to simplify the case for cross-compilation.
+    AR="m68k-unknown-linux-gnu-ar" CC="m68k-unknown-linux-gnu-gcc" cargo build --target $TARGET_TRIPLE
```
Comment (antoyo) [inline build_sysroot/build_sysroot.sh:26]: With the flag `--features compiler_builtins/c` removed, perhaps we can stop setting `RUST_COMPILER_RT_ROOT` and cloning the LLVM repo.

**Comment by antoyo** [comment]
Do not forget to update the cross-compiling instructions in the readme.

File: m68k-test/src/main.rs [hunk 2]
```diff
@@ -0,0 +1,10 @@
+use gccjit::{Context, FunctionType, OutputKind};
```
Comment (antoyo) [inline m68k-test/src/main.rs:1]: Do not forget to remove.
