### PR TITLE
Stop swallowing signals in build_system when running sub-commands

### LINKED ISSUE #496: y.sh cargo run swallows the signal emitted by the running process
For instance, if the process segfaults, `./y.sh cargo run` will not emit a SIGSEGV signal while it should do that.

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #496.

### CODE REVIEW

File: build_system/src/utils.rs [hunk 1]
```diff
@@ -2,9 +2,30 @@ use std::collections::HashMap;
...
+) -> Result<ExitStatus, String> {
+    let status = get_command_inner(input, cwd, env)
+        .spawn()
+        .map_err(|e| command_error(input, &cwd, e))?
+        .wait()
+        .map_err(|e| command_error(input, &cwd, e))?;
+    #[cfg(unix)]
+    {
+        if let Some(signal) = status.signal() {
+            return Err(command_error(input, &cwd, format!("Process received signal {}", signal)));
```
Comment (antoyo) [inline build_system/src/utils.rs:23]: I would prefer that you follow the same behavior as `cargo`, which is to emit the signal of the process so that the shell sees it.

Comment (GuillaumeGomez) [reply build_system/src/utils.rs:23]: Fine by me.

**Review by antoyo — APPROVED** [review]
