### PR TITLE
Fix asm pointer inputs

### LINKED ISSUE #792: Failure to build rustix@0.38.44 crate for ruffle
```
$ git clone https://github.com/ruffle-rs/ruffle
$ git rev-parse HEAD
1aad9ba00001103b7c1309fff3e7e3f650cd5d17
$ cargo build --release --jobs=1 --keep-going
   Compiling serde v1.0.228
   Compiling rustix v0.38.44
libgccjit.so: error: : gcc_jit_block_add_assignment: mismatching types: assignment to input_register (type: __int8_t *) from param1 (type: restrict __int32_t  __attribute__((aligned(4))) *)
error: failed to build archive at `/tmp/ruffle/target/release/deps/librustix-47bdde230005a84a.rlib`: failed to open object file: No such file or directory (os error 2)

fatal runtime error: failed to initiate panic, error 5, aborting
error: could not compile `rustix` (lib) due to 1 previous error

Caused by:
  process didn't exit successfully: `rustc --crate-name rustix --edition=2021 /home/sam/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rustix-0.38.44/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=186 --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C panic=abort -C embed-bitcode=no --warn=unexpected_cfgs --check-cfg 'cfg(alloc_c_string)' --check-cfg 'cfg(alloc_ffi)' --check-cfg 'cfg(apple)' --check-cfg 'cfg(asm_experimental_arch)' --check-cfg 'cfg(bsd)' --check-cfg 'cfg(core_c_str)' --check-cfg 'cfg(core_ffi_c)' --check-cfg 'cfg(core_intrinsics)' --check-cfg 'cfg(criterion)' --check-cfg 'cfg(document_experimental_runtime_api)' --check-cfg 'cfg(fix_y2038)' --check-cfg 'cfg(freebsdlike)' --check-cfg 'cfg(libc)' --check-cfg 'cfg(linux_kernel)' --check-cfg 'cfg(linux_like)' --check-cfg 'cfg(linux_raw)' --check-cfg 'cfg(netbsdlike)' --check-cfg 'cfg(rustc_attrs)' --check-cfg 'cfg(solarish)' --check-cfg 'cfg(staged_api)' --check-cfg 'cfg(static_assertions)' --check-cfg 'cfg(thumb_mode)' --check-cfg 'cfg(wasi)' --check-cfg 'cfg(wasi_ext)' --check-cfg 'cfg(target_arch, values("xtensa"))' --cfg 'feature="alloc"' --cfg 'feature="default"' --cfg 'feature="event"' --cfg 'feature="fs"' --cfg 'feature="libc-extra-traits"' --cfg 'feature="net"' --cfg 'feature="pipe"' --cfg 'feature="process"' --cfg 'feature="shm"' --cfg 'feature="std"' --cfg 'feature="system"' --cfg 'feature="thread"' --cfg 'feature="use-libc-auxv"' --check-cfg 'cfg(docsrs,test)' --check-cfg 'cfg(feature, values("all-apis", "alloc", "cc", "compiler_builtins", "core", "default", "event", "fs", "io_uring", "itoa", "libc", "libc-extra-traits", "libc_errno", "linux_4_11", "linux_latest", "mm", "mount", "net", "once_cell", "param", "pipe", "process", "procfs", "pty", "rand", "runtime", "rustc-dep-of-std", "rustc-std-workspace-alloc", "shm", "std", "stdio", "system", "termios", "thread", "time", "try_close", "use-explicitly-provided-auxv", "use-libc", "use-libc-auxv"))' -C metadata=d8bb571a3cacf652 -C extra-filename=-47bdde230005a84a --out-dir /tmp/ruffle/target/release/deps -C strip=debuginfo -L dependency=/tmp/ruffle/target/release/deps --extern bitflags=/tmp/ruffle/target/release/deps/libbitflags-ce0d2b8259a45f27.rmeta --extern linux_raw_sys=/tmp/ruffle/target/release/deps/liblinux_raw_sys-e1826575f169c49a.rmeta --cap-lints allow --cfg=web_sys_unstable_apis --cfg static_assertions --cfg linux_raw --cfg linux_like --cfg linux_kernel` (signal: 6, SIGABRT: process abort signal)
```

```
$ rustc -vV
rustc 1.91.0-nightly (21cd82aa6 2025-10-08) (gentoo)
binary: rustc
commit-hash: 21cd82aa6363f7ceaebefafc528e62124267461c
commit-date: 2025-10-08
host: x86_64-unknown-linux-gnu
release: 1.91.0-nightly
```

This is with the rust 1.91.0 beta from 20251009 and github.com/rust-lang/rust from b93730ce97c738bdb9209aa973d3fc6fd4ce1d81.

### PR DESCRIPTION
**Pull request by cijiugechu**
Typed pointer inputs to explicit registers need a cast.

Closes rust-lang/rustc_codegen_gcc#792

### CODE REVIEW

File: src/asm.rs [hunk 1]
```diff
@@ -362,7 +362,13 @@ impl<'a, 'gcc, 'tcx> AsmBuilderMethods<'tcx> for Builder<'a, 'gcc, 'tcx> {
                         let ty = value.layout.gcc_type(self.cx);
                         let reg_var = self.current_func().new_local(None, ty, "input_register");
                         reg_var.set_register_name(reg_name);
-                        self.llbb().add_assignment(None, reg_var, value.immediate());
+                        let value = value.immediate();
+                        let value = if value.get_type() != ty {
+                            self.context.new_cast(None, value, ty)
```
Comment (antoyo) [inline src/asm.rs:368]: Could you please add a `TODO` comment that mentions we should remove this when switching to "untyped" pointers?

**Review by antoyo — COMMENTED** [review]
Thanks for the fix!
One comment to add:

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rustc_codegen_gcc/874/9886ca55fdba1339f6811bee3cbb5a75229d3ccd..f939cb628fed4c72fe85675951ed4fee752d7de8)*

File: src/asm.rs (hunk 1 above)
Comment (cijiugechu) [reply src/asm.rs:368]: Added

Comment (antoyo) [reply src/asm.rs:368]: Oh sorry, it should have been a FIXME since we're now removing TODOs in #861.
Could you please switch it to a FIXME?

Comment (cijiugechu) [reply src/asm.rs:368]: Done

**Review by antoyo — APPROVED** [review]

**Comment by antoyo** [comment]
Thanks for your contribution!
