### PR TITLE
Fix ICE when calling transmuted function pointers

### LINKED ISSUE #836: ICE: `gcc_jit_context_new_call_through_ptr: not enough arguments to fn_ptr`
snippet:
````rust
//@compile-flags: -Zcodegen-backend=gcc -Clink-dead-code=true --crate-type=lib
extern "C" fn third(_a: usize, b: usize, c: usize) {
    let throw_away_f: fn((), usize, usize) =
        unsafe { std::mem::transmute(third as extern "C" fn(_, _, _)) };
    throw_away_f((), 2, 3)
}

````

Version information
````
rustc 1.95.0-nightly (a18e6d9d1 2026-01-24)
binary: rustc
commit-hash: a18e6d9d1473d9b25581dd04bef6c7577999631c
commit-date: 2026-01-24
host: x86_64-unknown-linux-gnu
release: 1.95.0-nightly
LLVM version: 21.1.8

````

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc -Zcodegen-backend=gcc -Clink-dead-code=true --crate-type=lib`

<details><summary><strong>Program output</strong></summary>
<p>

```
warning: unused variable: `b`
 --> /tmp/icemaker_global_tempdir.CBsLkoeTYAlI/rustc_testrunner_tmpdir_reporting.Dz5kKkoF2a7R/mvce.rs:1:32
  |
1 | extern "C" fn third(_a: usize, b: usize, c: usize) {
  |                                ^ help: if this is intentional, prefix it with an underscore: `_b`
  |
  = note: `#[warn(unused_variables)]` (part of `#[warn(unused)]`) on by default

warning: unused variable: `c`
 --> /tmp/icemaker_global_tempdir.CBsLkoeTYAlI/rustc_testrunner_tmpdir_reporting.Dz5kKkoF2a7R/mvce.rs:1:42
  |
1 | extern "C" fn third(_a: usize, b: usize, c: usize) {
  |                                          ^ help: if this is intentional, prefix it with an underscore: `_c`

warning: function `third` is never used
 --> /tmp/icemaker_global_tempdir.CBsLkoeTYAlI/rustc_testrunner_tmpdir_reporting.Dz5kKkoF2a7R/mvce.rs:1:15
  |
1 | extern "C" fn third(_a: usize, b: usize, c: usize) {
  |               ^^^^^
  |
  = note: `#[warn(dead_code)]` (part of `#[warn(unused)]`) on by default

libgccjit.so: error: : gcc_jit_context_new_call_through_ptr: not enough arguments to fn_ptr: _RNvCslo6T07L1JGf_4mvce5third (got 2 args, expected 3)
libgccjit.so: error: : gcc_jit_block_add_eval: NULL rvalue
error: failed to build archive at `outputfile`: failed to open object file: No such file or directory (os error 2)

error: aborting due to 1 previous error; 3 warnings emitted


```

</p>
</details>

### PR DESCRIPTION
**Pull request by cijiugechu**
Indirect calls could keep the original libgccjit function-pointer type after a transmute instead of the ABI-lowered type expected at the call site, so ZST-elided arguments made libgccjit see the wrong arity and ICE. Cast the callee to the call-site function-pointer type before emitting the indirect call so argument checking and codegen use the normalized signature.

Closes: rust-lang/rustc_codegen_gcc#836

### CODE REVIEW

File: tests/compile/fn_ptr_transmute_ignored_arg.rs [hunk 1]
```diff
@@ -0,0 +1,11 @@
+// Compiler:
+
+// Regression test for <https://github.com/rust-lang/rustc_codegen_gcc/issues/836>
+
+#![crate_type = "lib"]
+
+extern "C" fn third(_a: usize, b: usize, c: usize) {
```
Comment (bjorn3) [inline tests/compile/fn_ptr_transmute_ignored_arg.rs:8]: *[View changes since the review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rustc_codegen_gcc/873/9886ca55fdba1339f6811bee3cbb5a75229d3ccd..e41c82ac0cc4798d452f1334a673f1071d713a29)*

```suggestion
#[unsafe(no_mangle)]
extern "C" fn third(_a: usize, b: usize, c: usize) {
```
otherwise it isn't codegened.

Comment (cijiugechu) [reply tests/compile/fn_ptr_transmute_ignored_arg.rs:8]: Updated.

File: src/builder.rs [hunk 2]
```diff
@@ -350,19 +347,26 @@ impl<'a, 'gcc, 'tcx> Builder<'a, 'gcc, 'tcx> {
...
+                typ
+            } else {
+                func_ptr_type
             }
         };
+        let gcc_func = func_ptr_type.dyncast_function_ptr_type().expect("function ptr");
+        let on_stack_param_indices = if let Some(fn_abi) = fn_abi {
+            fn_abi.gcc_type(self.cx).on_stack_param_indices
+        } else {
+            self.on_stack_params.borrow().get(&gcc_func).cloned().unwrap_or_default()
```
Comment (antoyo) [inline src/builder.rs]: Do you know if we should expect `on_stack_params` to ever be non-empty in this branch?
I.e. would `fn_abi` always be `Some` when having on-stack parameters?

File: tests/compile/fn_ptr_transmute_ignored_arg.rs [hunk 3]
```diff
@@ -0,0 +1,12 @@
+// Compiler:
```
Comment (antoyo) [inline tests/compile/fn_ptr_transmute_ignored_arg.rs:1]: It seems this PR have fixed the test `tests/ui/backtrace/dylib-dep.rs`, so please remove it from the file `failing-ui-tests.txt`.

**Review by antoyo — COMMENTED** [review]
Thanks for your work.

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rustc_codegen_gcc/873/9886ca55fdba1339f6811bee3cbb5a75229d3ccd..c8634656fe12f1a1dada0b095364349b1fa6c1a1)*

File: src/builder.rs (hunk 2 above)
Comment (bjorn3) [reply src/builder.rs]: I think on-stack parameters don't happen for non-surface level calls (that is calls that don't have a Call terminator at the MIR level) and we should be passing fn_abi for all surface level calls.

File: tests/compile/fn_ptr_transmute_ignored_arg.rs (hunk 3 above)
Comment (cijiugechu) [reply tests/compile/fn_ptr_transmute_ignored_arg.rs:1]: Removed

**Review by antoyo — APPROVED** [review]
Nice work.
I'll try to merge my sync PR soon so that we can merge this PR afterwards.

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rustc_codegen_gcc/873/9886ca55fdba1339f6811bee3cbb5a75229d3ccd..308452042def5d5d997ddb81da65a3fcbaeebf04)*

**Comment by antoyo** [comment]
Thanks for your contribution!
