### PR TITLE
Always add git user info to run_command

### LINKED ISSUE #731: ./y.sh prepare patch does not apply
Trying to run `./y.sh prepare` in a current clone with the example config copied over and using a local gcc build:

```
root@d60bd2eeb984:/w/rustc_codegen_gcc# ./y.sh prepare      
[BUILD] build system
    Finished `release` profile [optimized] target(s) in 0.01s
[GIT] init (cwd): `build/build_sysroot/sysroot_src`
[GIT] add (cwd): `build/build_sysroot/sysroot_src`
[GIT] commit (cwd): `build/build_sysroot/sysroot_src`
[GIT] apply `patches/0001-Add-stdarch-Cargo.toml-for-testing.patch`
[master 6281c97] Patch ../../../patches/0001-Add-stdarch-Cargo.toml-for-testing.patch
 1 file changed, 21 insertions(+)
 create mode 100644 library/stdarch/Cargo.toml
[GIT] apply `patches/0028-core-Disable-long-running-tests.patch`
[master f8fb931] Patch ../../../patches/0028-core-Disable-long-running-tests.patch
 1 file changed, 2 insertions(+)
Successfully prepared libcore for building
`rand` has already been cloned
`regex` has already been cloned
`simple-raytracer` has already been cloned
[GIT] apply `patches/crates/0001-Remove-deny-warnings.patch`
error: patch failed: src/lib.rs:47
error: src/lib.rs: patch does not apply
Command `["git", "apply", "../../patches/crates/0001-Remove-deny-warnings.patch"]` failed
Command failed to run: Command `git apply ../../patches/crates/0001-Remove-deny-warnings.patch` (running in folder `build/rand`) exited with status Some(1)
```

Removing the `prepare_rand()?;` in `build_system/src/prepare.rs` fixed it for me. build/rand looks like rand 0.9.0.

### PR DESCRIPTION
**Pull request by dvermd**
This PR always pass the `user.name`, `user.email`, `core.autocrlf` and `commit.gpgSign` git parameters to the `run_command` and `run_command_with_output` functions.

With this PR, I managed to successfully run `./y.sh prepare` after a `./y.sh clean all" with and without `user.name` and `user.email` parameters defined for the repo.

Fixes rust-lang/rustc_codegen_gcc#731

### CODE REVIEW

File: build_system/src/prepare.rs [hunk 1]
```diff
@@ -1,12 +1,66 @@
...
+        &"core.autocrlf=false" as &dyn AsRef<OsStr>,
+        &"-c" as &dyn AsRef<OsStr>,
+        &"commit.gpgSign=false" as &dyn AsRef<OsStr>,
+    ]
+    .into_iter()
+    .chain([command])
+    .chain(input.iter().cloned())
+    .collect::<Vec<_>>()[..];
+    run_command_with_output(git_cmd, cwd)
+}
```
Comment (antoyo) [inline build_system/src/prepare.rs:62]: There's some duplication between these 2 functions.
Could you please refactor these functions to avoid this?

Comment (dvermd) [reply build_system/src/prepare.rs]: Moved the command definitions to a const

**Review by GuillaumeGomez — APPROVED** [review]
Looks good to me as well.

**Comment by antoyo** [comment]
Thanks for your work and sorry for the delay before reviewing your changes.
